
package es.rickyepoderi.managertest.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SessionTest", targetNamespace = "http://server.managertest.rickyepoderi.es/", wsdlLocation = "http://192.168.122.22:8080/manager-test/SessionTest?wsdl")
public class SessionTest_Service
    extends Service
{

    private final static URL SESSIONTEST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.rickyepoderi.managertest.client.SessionTest_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.rickyepoderi.managertest.client.SessionTest_Service.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.122.22:8080/manager-test/SessionTest?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.122.22:8080/manager-test/SessionTest?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SESSIONTEST_WSDL_LOCATION = url;
    }

    public SessionTest_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionTest_Service() {
        super(SESSIONTEST_WSDL_LOCATION, new QName("http://server.managertest.rickyepoderi.es/", "SessionTest"));
    }

    /**
     * 
     * @return
     *     returns SessionTest
     */
    @WebEndpoint(name = "SessionTestPort")
    public SessionTest getSessionTestPort() {
        return super.getPort(new QName("http://server.managertest.rickyepoderi.es/", "SessionTestPort"), SessionTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionTest
     */
    @WebEndpoint(name = "SessionTestPort")
    public SessionTest getSessionTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.managertest.rickyepoderi.es/", "SessionTestPort"), SessionTest.class, features);
    }

}
