
package es.rickyepoderi.managertest.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SessionTest", targetNamespace = "http://server.managertest.rickyepoderi.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SessionTest {


    /**
     * 
     * @param num
     * @param value
     * @param sleep
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CreateSession")
    @ResponseWrapper(localName = "createSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CreateSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/createSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/createSessionResponse")
    public String createSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "size", targetNamespace = "")
        int size,
        @WebParam(name = "value", targetNamespace = "")
        byte value,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSession")
    @ResponseWrapper(localName = "deleteSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/deleteSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/deleteSessionResponse")
    public String deleteSession(
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param value
     * @param sleep
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSession")
    @ResponseWrapper(localName = "updateSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/updateSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/updateSessionResponse")
    public String updateSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "size", targetNamespace = "")
        int size,
        @WebParam(name = "value", targetNamespace = "")
        byte value,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refreshSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.RefreshSession")
    @ResponseWrapper(localName = "refreshSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.RefreshSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/refreshSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/refreshSessionResponse")
    public String refreshSession(
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param value
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSeveralSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSeveralSession")
    @ResponseWrapper(localName = "updateSeveralSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSeveralSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/updateSeveralSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/updateSeveralSessionResponse")
    public String updateSeveralSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "value", targetNamespace = "")
        byte value,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param value
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CheckSession")
    @ResponseWrapper(localName = "checkSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CheckSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/checkSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/checkSessionResponse")
    public String checkSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "value", targetNamespace = "")
        byte value,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkNullSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CheckNullSession")
    @ResponseWrapper(localName = "checkNullSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CheckNullSessionResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/checkNullSessionRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/checkNullSessionResponse")
    public String checkNullSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSessionAttribute", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSessionAttribute")
    @ResponseWrapper(localName = "deleteSessionAttributeResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSessionAttributeResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/deleteSessionAttributeRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/deleteSessionAttributeResponse")
    public String deleteSessionAttribute(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param num
     * @param value
     * @param sleep
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSessionAttribute", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.AddSessionAttribute")
    @ResponseWrapper(localName = "addSessionAttributeResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.AddSessionAttributeResponse")
    @Action(input = "http://server.managertest.rickyepoderi.es/SessionTest/addSessionAttributeRequest", output = "http://server.managertest.rickyepoderi.es/SessionTest/addSessionAttributeResponse")
    public String addSessionAttribute(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "size", targetNamespace = "")
        int size,
        @WebParam(name = "value", targetNamespace = "")
        byte value,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

}
