
package es.rickyepoderi.managertest.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SessionTest", targetNamespace = "http://server.managertest.rickyepoderi.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SessionTest {


    /**
     * 
     * @param num
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CreateSession")
    @ResponseWrapper(localName = "createSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.CreateSessionResponse")
    public String createSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "size", targetNamespace = "")
        int size);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSession")
    @ResponseWrapper(localName = "deleteSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.DeleteSessionResponse")
    public String deleteSession();

    /**
     * 
     * @param num
     * @param sleep
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSession")
    @ResponseWrapper(localName = "updateSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.UpdateSessionResponse")
    public String updateSession(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "size", targetNamespace = "")
        int size,
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

    /**
     * 
     * @param sleep
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refreshSession", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.RefreshSession")
    @ResponseWrapper(localName = "refreshSessionResponse", targetNamespace = "http://server.managertest.rickyepoderi.es/", className = "es.rickyepoderi.managertest.client.RefreshSessionResponse")
    public String refreshSession(
        @WebParam(name = "sleep", targetNamespace = "")
        int sleep);

}
